name: Local CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted    # this tells GitHub to use YOUR PC

    steps:
      - uses: actions/checkout@v3
      - run: docker-compose down
      - run: docker-compose up -d --build
